/* This file is generated by cbindgen. Do not edit by hand.
 * Regenerate with: cbindgen --config cbindgen.toml --crate nsfoo --output nsfoo_ffi.h
 */

/* Warning: This file is autogenerated by cbindgen. Do not edit manually. */

#ifndef fox_nsfoo_ffi_h
#define fox_nsfoo_ffi_h

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif  /* __cplusplus */

/**
 * Opaque handle for nsFoo. Heap-allocated and owned by the caller.
 * Always free with fox_nsfoo_free().
 */
typedef struct FoxNsFoo FoxNsFoo;

/**
 * Allocate a new FoxNsFoo with the given initial value.
 * Returns NULL on allocation failure.
 * The caller must call fox_nsfoo_free() exactly once on the returned pointer.
 */
FoxNsFoo *fox_nsfoo_new(int initial);

/**
 * Free a FoxNsFoo previously returned by fox_nsfoo_new().
 * Passing NULL is safe and has no effect.
 */
void fox_nsfoo_free(FoxNsFoo *ptr);

/**
 * Return value + x (wrapping addition).
 * Returns -1 if ptr is NULL.
 */
int fox_nsfoo_bar(const FoxNsFoo *ptr, int x);

/**
 * Set the stored value.
 * Has no effect if ptr is NULL.
 */
void fox_nsfoo_set_value(FoxNsFoo *ptr, int v);

#ifdef __cplusplus
}  /* extern "C" */
#endif  /* __cplusplus */

#endif  /* fox_nsfoo_ffi_h */
